semi: true
tabWidth: 2
printWidth: 100
singleQuote: true
trailingComma: 'none'
bracketSameLine: true
importOrder:
  - '^components/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
endOfLine: 'auto'
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-organize-imports'
